# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\gianc\source\repos\CMakeProjectRaylib_TEST\CMakeProjectRaylib_TEST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\gianc\source\repos\CMakeProjectRaylib_TEST\CMakeProjectRaylib_TEST\build_web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gianc\source\repos\CMakeProjectRaylib_TEST\CMakeProjectRaylib_TEST\build_web\CMakeFiles C:\Users\gianc\source\repos\CMakeProjectRaylib_TEST\CMakeProjectRaylib_TEST\build_web\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gianc\source\repos\CMakeProjectRaylib_TEST\CMakeProjectRaylib_TEST\build_web\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f raylib\raylib\CMakeFiles\raylib.dir\build.make raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

Entity_cpp/Entity.o: Entity_cpp/Entity.cpp.o
.PHONY : Entity_cpp/Entity.o

# target to build an object file
Entity_cpp/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/Entity_cpp/Entity.cpp.o
.PHONY : Entity_cpp/Entity.cpp.o

Entity_cpp/Entity.i: Entity_cpp/Entity.cpp.i
.PHONY : Entity_cpp/Entity.i

# target to preprocess a source file
Entity_cpp/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/Entity_cpp/Entity.cpp.i
.PHONY : Entity_cpp/Entity.cpp.i

Entity_cpp/Entity.s: Entity_cpp/Entity.cpp.s
.PHONY : Entity_cpp/Entity.s

# target to generate assembly for a file
Entity_cpp/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/Entity_cpp/Entity.cpp.s
.PHONY : Entity_cpp/Entity.cpp.s

blocks.o: blocks.cpp.o
.PHONY : blocks.o

# target to build an object file
blocks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/blocks.cpp.o
.PHONY : blocks.cpp.o

blocks.i: blocks.cpp.i
.PHONY : blocks.i

# target to preprocess a source file
blocks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/blocks.cpp.i
.PHONY : blocks.cpp.i

blocks.s: blocks.cpp.s
.PHONY : blocks.s

# target to generate assembly for a file
blocks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/blocks.cpp.s
.PHONY : blocks.cpp.s

camera_cpp/camera.o: camera_cpp/camera.cpp.o
.PHONY : camera_cpp/camera.o

# target to build an object file
camera_cpp/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/camera_cpp/camera.cpp.o
.PHONY : camera_cpp/camera.cpp.o

camera_cpp/camera.i: camera_cpp/camera.cpp.i
.PHONY : camera_cpp/camera.i

# target to preprocess a source file
camera_cpp/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/camera_cpp/camera.cpp.i
.PHONY : camera_cpp/camera.cpp.i

camera_cpp/camera.s: camera_cpp/camera.cpp.s
.PHONY : camera_cpp/camera.s

# target to generate assembly for a file
camera_cpp/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/camera_cpp/camera.cpp.s
.PHONY : camera_cpp/camera.cpp.s

chunk_cpp/chunk.o: chunk_cpp/chunk.cpp.o
.PHONY : chunk_cpp/chunk.o

# target to build an object file
chunk_cpp/chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/chunk_cpp/chunk.cpp.o
.PHONY : chunk_cpp/chunk.cpp.o

chunk_cpp/chunk.i: chunk_cpp/chunk.cpp.i
.PHONY : chunk_cpp/chunk.i

# target to preprocess a source file
chunk_cpp/chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/chunk_cpp/chunk.cpp.i
.PHONY : chunk_cpp/chunk.cpp.i

chunk_cpp/chunk.s: chunk_cpp/chunk.cpp.s
.PHONY : chunk_cpp/chunk.s

# target to generate assembly for a file
chunk_cpp/chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/chunk_cpp/chunk.cpp.s
.PHONY : chunk_cpp/chunk.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/main.cpp.s
.PHONY : main.cpp.s

mouse_cpp/mouseDirectionSeeing.o: mouse_cpp/mouseDirectionSeeing.cpp.o
.PHONY : mouse_cpp/mouseDirectionSeeing.o

# target to build an object file
mouse_cpp/mouseDirectionSeeing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/mouse_cpp/mouseDirectionSeeing.cpp.o
.PHONY : mouse_cpp/mouseDirectionSeeing.cpp.o

mouse_cpp/mouseDirectionSeeing.i: mouse_cpp/mouseDirectionSeeing.cpp.i
.PHONY : mouse_cpp/mouseDirectionSeeing.i

# target to preprocess a source file
mouse_cpp/mouseDirectionSeeing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/mouse_cpp/mouseDirectionSeeing.cpp.i
.PHONY : mouse_cpp/mouseDirectionSeeing.cpp.i

mouse_cpp/mouseDirectionSeeing.s: mouse_cpp/mouseDirectionSeeing.cpp.s
.PHONY : mouse_cpp/mouseDirectionSeeing.s

# target to generate assembly for a file
mouse_cpp/mouseDirectionSeeing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/mouse_cpp/mouseDirectionSeeing.cpp.s
.PHONY : mouse_cpp/mouseDirectionSeeing.cpp.s

movement_cpp/collisionCheck.o: movement_cpp/collisionCheck.cpp.o
.PHONY : movement_cpp/collisionCheck.o

# target to build an object file
movement_cpp/collisionCheck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/collisionCheck.cpp.o
.PHONY : movement_cpp/collisionCheck.cpp.o

movement_cpp/collisionCheck.i: movement_cpp/collisionCheck.cpp.i
.PHONY : movement_cpp/collisionCheck.i

# target to preprocess a source file
movement_cpp/collisionCheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/collisionCheck.cpp.i
.PHONY : movement_cpp/collisionCheck.cpp.i

movement_cpp/collisionCheck.s: movement_cpp/collisionCheck.cpp.s
.PHONY : movement_cpp/collisionCheck.s

# target to generate assembly for a file
movement_cpp/collisionCheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/collisionCheck.cpp.s
.PHONY : movement_cpp/collisionCheck.cpp.s

movement_cpp/movement.o: movement_cpp/movement.cpp.o
.PHONY : movement_cpp/movement.o

# target to build an object file
movement_cpp/movement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/movement.cpp.o
.PHONY : movement_cpp/movement.cpp.o

movement_cpp/movement.i: movement_cpp/movement.cpp.i
.PHONY : movement_cpp/movement.i

# target to preprocess a source file
movement_cpp/movement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/movement.cpp.i
.PHONY : movement_cpp/movement.cpp.i

movement_cpp/movement.s: movement_cpp/movement.cpp.s
.PHONY : movement_cpp/movement.s

# target to generate assembly for a file
movement_cpp/movement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/movement_cpp/movement.cpp.s
.PHONY : movement_cpp/movement.cpp.s

particles_cpp/particles.o: particles_cpp/particles.cpp.o
.PHONY : particles_cpp/particles.o

# target to build an object file
particles_cpp/particles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/particles_cpp/particles.cpp.o
.PHONY : particles_cpp/particles.cpp.o

particles_cpp/particles.i: particles_cpp/particles.cpp.i
.PHONY : particles_cpp/particles.i

# target to preprocess a source file
particles_cpp/particles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/particles_cpp/particles.cpp.i
.PHONY : particles_cpp/particles.cpp.i

particles_cpp/particles.s: particles_cpp/particles.cpp.s
.PHONY : particles_cpp/particles.s

# target to generate assembly for a file
particles_cpp/particles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/particles_cpp/particles.cpp.s
.PHONY : particles_cpp/particles.cpp.s

rendering/GUI_cpp/GUI.o: rendering/GUI_cpp/GUI.cpp.o
.PHONY : rendering/GUI_cpp/GUI.o

# target to build an object file
rendering/GUI_cpp/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/GUI.cpp.o
.PHONY : rendering/GUI_cpp/GUI.cpp.o

rendering/GUI_cpp/GUI.i: rendering/GUI_cpp/GUI.cpp.i
.PHONY : rendering/GUI_cpp/GUI.i

# target to preprocess a source file
rendering/GUI_cpp/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/GUI.cpp.i
.PHONY : rendering/GUI_cpp/GUI.cpp.i

rendering/GUI_cpp/GUI.s: rendering/GUI_cpp/GUI.cpp.s
.PHONY : rendering/GUI_cpp/GUI.s

# target to generate assembly for a file
rendering/GUI_cpp/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/GUI.cpp.s
.PHONY : rendering/GUI_cpp/GUI.cpp.s

rendering/GUI_cpp/hotBar.o: rendering/GUI_cpp/hotBar.cpp.o
.PHONY : rendering/GUI_cpp/hotBar.o

# target to build an object file
rendering/GUI_cpp/hotBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/hotBar.cpp.o
.PHONY : rendering/GUI_cpp/hotBar.cpp.o

rendering/GUI_cpp/hotBar.i: rendering/GUI_cpp/hotBar.cpp.i
.PHONY : rendering/GUI_cpp/hotBar.i

# target to preprocess a source file
rendering/GUI_cpp/hotBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/hotBar.cpp.i
.PHONY : rendering/GUI_cpp/hotBar.cpp.i

rendering/GUI_cpp/hotBar.s: rendering/GUI_cpp/hotBar.cpp.s
.PHONY : rendering/GUI_cpp/hotBar.s

# target to generate assembly for a file
rendering/GUI_cpp/hotBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/GUI_cpp/hotBar.cpp.s
.PHONY : rendering/GUI_cpp/hotBar.cpp.s

rendering/redering.o: rendering/redering.cpp.o
.PHONY : rendering/redering.o

# target to build an object file
rendering/redering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/redering.cpp.o
.PHONY : rendering/redering.cpp.o

rendering/redering.i: rendering/redering.cpp.i
.PHONY : rendering/redering.i

# target to preprocess a source file
rendering/redering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/redering.cpp.i
.PHONY : rendering/redering.cpp.i

rendering/redering.s: rendering/redering.cpp.s
.PHONY : rendering/redering.s

# target to generate assembly for a file
rendering/redering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/rendering/redering.cpp.s
.PHONY : rendering/redering.cpp.s

usefullFunc_cpp/usefullFunc.o: usefullFunc_cpp/usefullFunc.cpp.o
.PHONY : usefullFunc_cpp/usefullFunc.o

# target to build an object file
usefullFunc_cpp/usefullFunc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/usefullFunc_cpp/usefullFunc.cpp.o
.PHONY : usefullFunc_cpp/usefullFunc.cpp.o

usefullFunc_cpp/usefullFunc.i: usefullFunc_cpp/usefullFunc.cpp.i
.PHONY : usefullFunc_cpp/usefullFunc.i

# target to preprocess a source file
usefullFunc_cpp/usefullFunc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/usefullFunc_cpp/usefullFunc.cpp.i
.PHONY : usefullFunc_cpp/usefullFunc.cpp.i

usefullFunc_cpp/usefullFunc.s: usefullFunc_cpp/usefullFunc.cpp.s
.PHONY : usefullFunc_cpp/usefullFunc.s

# target to generate assembly for a file
usefullFunc_cpp/usefullFunc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game.dir\build.make CMakeFiles/game.dir/usefullFunc_cpp/usefullFunc.cpp.s
.PHONY : usefullFunc_cpp/usefullFunc.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... game
	@echo ... raylib
	@echo ... Entity_cpp/Entity.o
	@echo ... Entity_cpp/Entity.i
	@echo ... Entity_cpp/Entity.s
	@echo ... blocks.o
	@echo ... blocks.i
	@echo ... blocks.s
	@echo ... camera_cpp/camera.o
	@echo ... camera_cpp/camera.i
	@echo ... camera_cpp/camera.s
	@echo ... chunk_cpp/chunk.o
	@echo ... chunk_cpp/chunk.i
	@echo ... chunk_cpp/chunk.s
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
	@echo ... mouse_cpp/mouseDirectionSeeing.o
	@echo ... mouse_cpp/mouseDirectionSeeing.i
	@echo ... mouse_cpp/mouseDirectionSeeing.s
	@echo ... movement_cpp/collisionCheck.o
	@echo ... movement_cpp/collisionCheck.i
	@echo ... movement_cpp/collisionCheck.s
	@echo ... movement_cpp/movement.o
	@echo ... movement_cpp/movement.i
	@echo ... movement_cpp/movement.s
	@echo ... particles_cpp/particles.o
	@echo ... particles_cpp/particles.i
	@echo ... particles_cpp/particles.s
	@echo ... rendering/GUI_cpp/GUI.o
	@echo ... rendering/GUI_cpp/GUI.i
	@echo ... rendering/GUI_cpp/GUI.s
	@echo ... rendering/GUI_cpp/hotBar.o
	@echo ... rendering/GUI_cpp/hotBar.i
	@echo ... rendering/GUI_cpp/hotBar.s
	@echo ... rendering/redering.o
	@echo ... rendering/redering.i
	@echo ... rendering/redering.s
	@echo ... usefullFunc_cpp/usefullFunc.o
	@echo ... usefullFunc_cpp/usefullFunc.i
	@echo ... usefullFunc_cpp/usefullFunc.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

